package com.spotifyhub.ui.common

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class LandscapeUiProfile(
    val isCompactHeight: Boolean,
    val outerHorizontalPadding: Dp,
    val outerVerticalPadding: Dp,
    val contentGap: Dp,
    val mainInnerHorizontalPadding: Dp,
    val mainInnerVerticalPadding: Dp,
    val sidebarWidth: Dp,
    val sidebarVerticalPadding: Dp,
    val sidebarHorizontalPadding: Dp,
    val sidebarIconSpacing: Dp,
    val sidebarIconSize: Dp,
    val sidebarTouchWidth: Dp,
    val sidebarTouchVerticalPadding: Dp,
    val clockFontSize: TextUnit,
    val typeScale: Float,
    val nowPlayingMetaWeight: Float,
    val nowPlayingArtworkWeight: Float,
    val nowPlayingHeroGap: Dp,
    val nowPlayingSectionGap: Dp,
    val nowPlayingProgressToUtilityGap: Dp,
    val nowPlayingTitleSize: TextUnit,
    val nowPlayingTitleLineHeight: TextUnit,
    val nowPlayingTitleMaxLines: Int,
    val nowPlayingArtistSize: TextUnit,
    val nowPlayingAlbumSize: TextUnit,
    val progressLabelSize: TextUnit,
    val transportSideButtonSize: Dp,
    val transportCenterButtonSize: Dp,
    val transportGap: Dp,
    val utilityButtonSpacing: Dp,
    val progressIdleTrackHeight: Dp,
    val progressDraggingTrackHeight: Dp,
    val quickAccessCardHeight: Dp,
    val quickAccessTitleSize: TextUnit,
    val browseSectionTitleSize: TextUnit,
    val browseCardWidth: Dp,
    val browseCardTitleSize: TextUnit,
    val browseCardSubtitleSize: TextUnit,
    val artistCardWidth: Dp,
    val artistCardTitleSize: TextUnit,
    val homeGreetingSize: TextUnit,
    val searchBarHeight: Dp,
    val searchInputSize: TextUnit,
    val searchSectionHeaderSize: TextUnit,
    val searchResultVerticalPadding: Dp,
    val libraryTitleSize: TextUnit,
    val libraryChipTextSize: TextUnit,
    val libraryChipVerticalPadding: Dp,
    val libraryRowVerticalPadding: Dp,
)

fun resolveLandscapeUiProfile(
    width: Dp,
    height: Dp,
): LandscapeUiProfile {
    val isCompactHeight = width > height &&
        (width.value / height.value) >= 1.75f &&
        minOf(width, height) <= 540.dp

    return if (isCompactHeight) {
        LandscapeUiProfile(
            isCompactHeight = true,
            outerHorizontalPadding = 8.dp,
            outerVerticalPadding = 8.dp,
            contentGap = 8.dp,
            mainInnerHorizontalPadding = 4.dp,
            mainInnerVerticalPadding = 3.dp,
            sidebarWidth = 54.dp,
            sidebarVerticalPadding = 10.dp,
            sidebarHorizontalPadding = 5.dp,
            sidebarIconSpacing = 8.dp,
            sidebarIconSize = 24.dp,
            sidebarTouchWidth = 44.dp,
            sidebarTouchVerticalPadding = 10.dp,
            clockFontSize = 15.sp,
            typeScale = 1.08f,
            nowPlayingMetaWeight = 0.56f,
            nowPlayingArtworkWeight = 0.44f,
            nowPlayingHeroGap = 12.dp,
            nowPlayingSectionGap = 12.dp,
            nowPlayingProgressToUtilityGap = 14.dp,
            nowPlayingTitleSize = 38.sp,
            nowPlayingTitleLineHeight = 42.sp,
            nowPlayingTitleMaxLines = 2,
            nowPlayingArtistSize = 22.sp,
            nowPlayingAlbumSize = 17.sp,
            progressLabelSize = 12.sp,
            transportSideButtonSize = 68.dp,
            transportCenterButtonSize = 82.dp,
            transportGap = 24.dp,
            utilityButtonSpacing = 20.dp,
            progressIdleTrackHeight = 5.dp,
            progressDraggingTrackHeight = 6.dp,
            quickAccessCardHeight = 58.dp,
            quickAccessTitleSize = 12.sp,
            browseSectionTitleSize = 22.sp,
            browseCardWidth = 126.dp,
            browseCardTitleSize = 13.sp,
            browseCardSubtitleSize = 11.sp,
            artistCardWidth = 104.dp,
            artistCardTitleSize = 12.sp,
            homeGreetingSize = 28.sp,
            searchBarHeight = 50.dp,
            searchInputSize = 17.sp,
            searchSectionHeaderSize = 18.sp,
            searchResultVerticalPadding = 8.dp,
            libraryTitleSize = 26.sp,
            libraryChipTextSize = 14.sp,
            libraryChipVerticalPadding = 10.dp,
            libraryRowVerticalPadding = 8.dp,
        )
    } else {
        LandscapeUiProfile(
            isCompactHeight = false,
            outerHorizontalPadding = 12.dp,
            outerVerticalPadding = 10.dp,
            contentGap = 12.dp,
            mainInnerHorizontalPadding = 6.dp,
            mainInnerVerticalPadding = 4.dp,
            sidebarWidth = 62.dp,
            sidebarVerticalPadding = 12.dp,
            sidebarHorizontalPadding = 6.dp,
            sidebarIconSpacing = 12.dp,
            sidebarIconSize = 26.dp,
            sidebarTouchWidth = 46.dp,
            sidebarTouchVerticalPadding = 10.dp,
            clockFontSize = 14.sp,
            typeScale = 1f,
            nowPlayingMetaWeight = 0.58f,
            nowPlayingArtworkWeight = 0.42f,
            nowPlayingHeroGap = 16.dp,
            nowPlayingSectionGap = 26.dp,
            nowPlayingProgressToUtilityGap = 12.dp,
            nowPlayingTitleSize = 34.sp,
            nowPlayingTitleLineHeight = 38.sp,
            nowPlayingTitleMaxLines = 2,
            nowPlayingArtistSize = 20.sp,
            nowPlayingAlbumSize = 16.sp,
            progressLabelSize = 11.sp,
            transportSideButtonSize = 72.dp,
            transportCenterButtonSize = 88.dp,
            transportGap = 34.dp,
            utilityButtonSpacing = 32.dp,
            progressIdleTrackHeight = 4.dp,
            progressDraggingTrackHeight = 5.dp,
            quickAccessCardHeight = 52.dp,
            quickAccessTitleSize = 11.sp,
            browseSectionTitleSize = 20.sp,
            browseCardWidth = 120.dp,
            browseCardTitleSize = 12.sp,
            browseCardSubtitleSize = 10.sp,
            artistCardWidth = 100.dp,
            artistCardTitleSize = 11.sp,
            homeGreetingSize = 26.sp,
            searchBarHeight = 44.dp,
            searchInputSize = 15.sp,
            searchSectionHeaderSize = 16.sp,
            searchResultVerticalPadding = 6.dp,
            libraryTitleSize = 24.sp,
            libraryChipTextSize = 13.sp,
            libraryChipVerticalPadding = 8.dp,
            libraryRowVerticalPadding = 8.dp,
        )
    }
}

@Composable
fun rememberLandscapeUiProfile(
    maxWidth: Dp,
    maxHeight: Dp,
): LandscapeUiProfile = remember(maxWidth, maxHeight) {
    resolveLandscapeUiProfile(maxWidth, maxHeight)
}
